package scripts.TFLAirRunecrafter;

public enum TFLAirRunecrafterENUM {
	DEPOSIT_RUNES, WITHDRAW_ESSENCE, WALK_TO_AIRRUINS, 
	ENTER_AIRRUINS, WALK_TO_ALTAR, CRAFT_RUNES,
	WALK_TO_PORTAL, ENTER_PORTAL, WALK_TO_BANK,
	OPEN_BANK;
}
